# Generated by Django 2.2 on 2019-10-29 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrderDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Euro amount')),
                ('flavours', models.CharField(default='', max_length=20)),
                ('count', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('regular', 'Regular'), ('medium', 'Medium'), ('large', 'Large')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'Inprogress'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('customer', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
